version: '3'
services:
  db:
    image: postgres:11.2-alpine
    ports:
      - "5432:5432"
    env_file: ./.env 
    container_name: chalendiary-db
    volumes:
      - postgresql-data:/var/lib/pgsql/11.2
      - /var/lib/pgsql/11.2/data
volumes:
  postgresql-data: