INSERT INTO replies(id, diary_id, user_id, content_text)
    VALUES
        (1, 1, 2, 'There is lot of hate out there for a text that amounts to little more than garbled words in an old language. The villagers are out there with a vengeance to get that Frankenstein, wielding torches and pitchforks, wanting to tar and feather it at the least, running it out of town in shame.'),
        (2, 1, 3, 'I have heard the argument that “lorem ipsum” is effective in wireframing or design because it helps people focus on the actual layout, or color scheme, or whatever. What kills me here is that we’re talking about creating a user experience that will (whether we like it or not) be DRIVEN by words. The entire structure of the page or app flow is FOR THE WORDS.'),
        (3, 2, 1, 'If that is what you think how bout the other way around? How can you evaluate content without design? No typography, no colors, no layout, no styles, all those things that convey the important signals that go beyond the mere textual, hierarchies of information, weight, emphasis, oblique stresses, priorities'),
        (4, 3, 1, 'All those subtle cues that also have visual and emotional appeal to the reader. Rigid proponents of content strategy may shun the use of dummy copy but then designers might want to ask them to provide style sheets with the copy decks they supply that are in tune with the design direction they require'),
        (5, 4, 4, 'Or else, an alternative route: set checkpoints, networks, processes, junctions between content and layout. Depending on the state of affairs it may be fine to concentrate either on design or content, reversing gears when needed.'),
        (6, 4, 5, 'Luke Wroblewski, currently a Product Director at Google, holds that fake data can break down in real life:'),
        (7, 6, 5, 'Using dummy content or fake information in the Web design process can result in products with unrealistic assumptions and potentially serious design flaws. '),
        (8, 7, 6, 'Websites in professional use templating systems. Commercial publishing platforms and content management systems ensure that you can show different text'),
        (9, 10, 7, 'Summing up, if the copy is diverting attention from the design it’s because it’s not up to task.'),
        (10, 10, 1, 'Lorem Ipsum is a tool that can be useful, used intentionally it may help solve some problems. If you go about content strategy the wrong way, fix that problem.'),
        (11, 11, 8, 'MS Word: From 2007 onwards typing =lorem(i) or =lorem(i, j) in MS Word creates greeking text--do not forget to hit the enter key; i and j need to be integers, where i stands for the amount of desired paragraphs and j numbers the sentences per paragraph. j has a default value of 3 and a maximum set to 6665.'),
        (12, 12, 7, 'Open Office: An extension named Magenta Lorem ipsum generator is available at services.openoffice.org. Once installed, an icon will be shown in a toolbar below the menu bar, with the option to insert a number of paragraphs, the maximum is set to 25. >> screenshots'),
        (13, 13, 2, 'Lorem Ipsum Generator: Creates a button on wysiwyg toolbars to add a configurable amount of Lorem Ipsum text to a post, page or any other custom post type.'),
        (14, 14, 2, 'Adobe Dreamweaver, a web development environment, has a plugin in form of a Dreamweaver object named Dreamweaver Text. It can be accessed both from the Objects menu via Common > Lorem Ipsum palette or using the Lorem Ipsum entry in the Insert > Technocurve Menu.'),
        (15, 23, 9, 'An alternative, possibly more versatile, is Lorem and More. It inserts dummy copy as paragraphs, lists, and regular text. Optionally available are extracts from a speech by Cicero, corporate nonsense, and a randomised sonnet by Shakespeare. Text may be inserted in code view and design view. The tool can be accessed via the Lorem and More icon on the Common tab of the Insert bar (MX) or the Common objects panel (DW4). Else, it is accessible using the menu: Insert > Lorem and More.'),
        (16, 24, 9, 'For notepad++, a Windows text editor, the InsertLoremIpsumNppPlugin can be downloaded at twenfour.com. It generates and inserts Lorem Ipsum, either as words, sentences, or paragraphs. The installation requires to copy the file InsertLoremIpsumNppPlugin.dll and the Config directory (both are contained in the zip file) to the "plugins" subdirectory of the Notepad++ installation directory. Afterwards, a new option "InsertLoremIpsum" will show in the "plugin" menu entry. A restart may be required.')
;